---
title: "R Notebook"
output: 
---

Set directory and way to access data
```{r}
library(here)
library(conflicted)
conflict_prefer("here", "here")
options(scipen=999)
library(Momocs)
```

Julien Caude's function from book 2008
```{r}
NEF2COE<-function (nef.path){
  nef <- readLines(nef.path)
  HARMO.l <- grep(pattern = "HARMO", nef)
  nb.h <- as.numeric(substring(nef[HARMO.l], 8))
  nef <- nef[-(1:HARMO.l)]
  nb.coo <- length(nef)/(nb.h + 1)
  coo.i <- 1:nb.coo
  coo.beg <- (coo.i - 1) * (nb.h + 1) + 1
  coo.end <- coo.beg + nb.h
  res <- matrix(NA, nrow = nb.coo, ncol = nb.h * 4, dimnames = list(nef[coo.beg], paste(rep(LETTERS[1:4], each = nb.h), 1:nb.h, sep = "")))
  for (i in seq(along = coo.i)) {
    nef.i <- nef[(coo.beg[i]+1):coo.end[i]]
    x <- as.numeric(unlist(strsplit(nef.i, " ")))
    x1<-x[!is.na(x)]
    a.i<-x1[seq(1,length(x1),4)]
    b.i<-x1[seq(2,length(x1),4)]
    c.i<-x1[seq(3,length(x1),4)]
    d.i<-x1[seq(4,length(x1),4)]
    res[i, ]<-c(a.i,b.i,c.i,d.i)
  }
  return(OutCoe(res,method="efourier", norm = FALSE))}
```


Load NEFD data
```{r}
nf <- NEF2COE(nef.path = "3_results/2_3_data_shape/nef/30specimens_clean.nef")
```


PCA on the original nefd coefficients (A-D) from SHAPE
```{r}
pca <- PCA(nf)
barplot(pca$eig)
plot(pca) # PCA on the full set of harmonics
 # the first harmonic has very large impact!
```


For new PCA, I  remove the effect of the 1st harmonic by assigning a constant value to D1 in all shapes. I replace the D1 values by the mean of this variable
```{r}
nf1 <- nf
nf1$coe[, 'D1'] <- mean(nf1$coe[,'D1'])
pca1 <- PCA(nf1)
barplot(pca1$eig)
plot(pca1)
```

Export figures to results
```{r}
# yes 1 pc
tiff(file = here::here("3_results", "fig_suppl2_1pc_yes.tiff"),  height= 10, width=18, units = 'cm', res = 300, compression = "lzw", family = "sans")
plot(pca)
dev.off()

# no 1 pc
tiff(file = here::here("3_results", "fig_suppl2_1pc_no.tiff"),  height= 10, width=18, units = 'cm', res = 300, compression = "lzw", family = "sans")
plot(pca1)
dev.off()
```


